### ISSUE TITLE
E-book versus Code No Match

### ISSUE THREAD

**Issue by drgaryholland** [PacktPublishing/Hands-On-Spring-Security-5-for-Reactive-Applications#1]
I'm trying to learn Spring and everything about it including security , when a book is published, and I read it and download the code for which the author provides I try to follow it. I am a disappointed reader on chapter 2 . Code does not match the chapter Tomcy John follow the book and create a project based on chapter 2, no source code code available, I'm just wondering , how can you author a book and not proof it to its entirety. Where is the code to chap 2!  I am frustrated with your book so far, I'm afraid I'm going to give you an "F", and let my students know your book is not finished.

**Comment by johntomcy** [comment]
@drgaryholland really sorry to hear this.
All the projects mentioned in the book and detailed (code snippets) is available as full-fledged runnable project in the Git hub repository. I have attached a number of screenshots in which i have tried to detail this.
![chapter2examples](https://user-images.githubusercontent.com/1597490/49201252-a656b600-f3b9-11e8-8c56-c628fe6807d1.PNG)
![bookref2](https://user-images.githubusercontent.com/1597490/49201257-aeaef100-f3b9-11e8-8b75-706a4d334303.PNG)
![bookref1](https://user-images.githubusercontent.com/1597490/49201258-aeaef100-f3b9-11e8-884d-4e24d38f3b95.PNG)
![bookref5](https://user-images.githubusercontent.com/1597490/49201259-af478780-f3b9-11e8-9c36-9e9dc46437ac.PNG)
![bookref4](https://user-images.githubusercontent.com/1597490/49201260-af478780-f3b9-11e8-97bc-4200f5e3bf8a.PNG)
![bookref3](https://user-images.githubusercontent.com/1597490/49201261-af478780-f3b9-11e8-9cfa-78ae52547f4c.PNG)

Please let me know if this answers your concerns.

**Comment by johntomcy** [comment]
Can you please let me know if your concern is addressed?

**Comment by johntomcy** [comment]
Closing the issue as the @drgaryholland didn't come back on the resolution provided.
