### ISSUE TITLE
Chapter 2 code is NOT COMPLETE

### ISSUE THREAD

**Issue by DavidSonoda** [PacktPublishing/Hands-On-Spring-Security-5-for-Reactive-Applications#2]
Hi John @johntomcy ,

I'm reading the Chapter 2 of the book and found that the sample application named `jetty-db-basic-authentication` is missing multiple code files. Specifically:

- Step 3 - MySQL database schema setup: sample `sql` script is missing
- Step 5 - Spring application configuration: `ApplicationConfig.java` is missing
- Step 6 - Web application configuration: `WebApplicationConfig.java` is missing
- Step 7 - missing
- Step 8 - missing
... etc

**Please check the integrity of your sample project files** and update this github repository, especially please upload the missing code part. Though I understand this might be an honest mistake and readers can complete the project according to the book, but this might be not acceptable for a book which has been published.

Thanks

**Comment by DavidSonoda** [comment]
Plus, in the 
- **Run as Spring Boot** section of Chapter 2, code in the `spring-boot-in-memory-basic-authentication` project is **empty**.

Please be advised to fix that.

**Comment by johntomcy** [comment]
> Hi John @johntomcy ,
> 
> I'm reading the Chapter 2 of the book and found that the sample application named `jetty-db-basic-authentication` is missing multiple code files. Specifically:
> 
> * Step 3 - MySQL database schema setup: sample `sql` script is missing
> * Step 5 - Spring application configuration: `ApplicationConfig.java` is missing
> * Step 6 - Web application configuration: `WebApplicationConfig.java` is missing
> * Step 7 - missing
> * Step 8 - missing
>   ... etc
> 
> **Please check the integrity of your sample project files** and update this github repository, especially please upload the missing code part. Though I understand this might be an honest mistake and readers can complete the project according to the book, but this might be not acceptable for a book which has been published.
> 
> Thanks

Really appreciate time taken to drop me an email to report this.
First of all, apologies.
Secondly, something really strange is happening. I seem to commit and push the changes (yes in the past also i have done it), but something just happens and i don't see some files later on.
It might seem a lame excuse.
Give me sometime and let me try sorting it out once again using my previous backup. Since i am stretched on time i might not be able to run the full code. But, let me at least try to commit these missing files first.

Apologies once again.

**Comment by johntomcy** [comment]
> Hi John @johntomcy ,
> 
> I'm reading the Chapter 2 of the book and found that the sample application named `jetty-db-basic-authentication` is missing multiple code files. Specifically:
> 
> * Step 3 - MySQL database schema setup: sample `sql` script is missing
> * Step 5 - Spring application configuration: `ApplicationConfig.java` is missing
> * Step 6 - Web application configuration: `WebApplicationConfig.java` is missing
> * Step 7 - missing
> * Step 8 - missing
>   ... etc
> 
> **Please check the integrity of your sample project files** and update this github repository, especially please upload the missing code part. Though I understand this might be an honest mistake and readers can complete the project according to the book, but this might be not acceptable for a book which has been published.
> 
> Thanks

Committed the missing files. Can you check and let me know please.
Sorry for the trouble.

Thanks

**Comment by DavidSonoda** [comment]
Thank you for your update! It would be very excited we can get access to the full code soon. 

As for potential issues of running. I believe it's not a big problem for now. I will be posing issues for running here if there are any problems. And I'll try to submit PR if possible (certainly obeying rules in your original book).

Lastly, thanks for writing this book. It's really hard to find good examples and fine elaboration with Reactive stacks as long as Spring Security Framework. I personally recommend you to keep your book updated and release future versions for new features in Spring Security if possible. Since reading the original Spring Security Reference Manual is really a pain in the ass for majority of developers who are relatively new to Spring stack.

Thanks a lot for your book and effort, I really appreciate that.

**Comment by DavidSonoda** [comment]
> > Hi John @johntomcy ,
> > I'm reading the Chapter 2 of the book and found that the sample application named `jetty-db-basic-authentication` is missing multiple code files. Specifically:
> > 
> > * Step 3 - MySQL database schema setup: sample `sql` script is missing
> > * Step 5 - Spring application configuration: `ApplicationConfig.java` is missing
> > * Step 6 - Web application configuration: `WebApplicationConfig.java` is missing
> > * Step 7 - missing
> > * Step 8 - missing
> >   ... etc
> > 
> > **Please check the integrity of your sample project files** and update this github repository, especially please upload the missing code part. Though I understand this might be an honest mistake and readers can complete the project according to the book, but this might be not acceptable for a book which has been published.
> > Thanks
> 
> Committed the missing files. Can you check and let me know please.
> Sorry for the trouble.
> 
> Thanks

Hi John,

The files are now complete for this part! 

But for 
- Run as Spring Boot section of Chapter 2, code in the spring-boot-in-memory-basic-authentication project is empty.

Could you please make that fix too? Thanks a lot.

**Comment by johntomcy** [comment]
> Plus, in the
> 
> * **Run as Spring Boot** section of Chapter 2, code in the `spring-boot-in-memory-basic-authentication` project is **empty**.
> 
> Please be advised to fix that.

Added missing files. Can you please check and confirm if it is good enough.

Thanks

**Comment by DavidSonoda** [comment]
Ah! Sorry! My mistake, it's complete now, probably my page refreshing issue. Thanks again!

**Comment by DavidSonoda** [comment]
I'll close this issue for now and reopen it if there are more missing.

**Comment by johntomcy** [comment]
> Hi John,
> 
> It's all complete now. Thanks a lot!

Thanks to you David. Once again, i really appreciate time taken to report this.

**Comment by johntomcy** [comment]
> Thank you for your update! It would be very excited we can get access to the full code soon.
> 
> As for potential issues of running. I believe it's not a big problem for now. I will be posing issues for running here if there are any problems. And I'll try to submit PR if possible (certainly obeying rules in your original book).
> 
> Lastly, thanks for writing this book. It's really hard to find good examples and fine elaboration with Reactive stacks as long as Spring Security Framework. I personally recommend you to keep your book updated and release future versions for new features in Spring Security if possible. Since reading the original Spring Security Reference Manual is really a pain in the ass for majority of developers who are relatively new to Spring stack.
> 
> Thanks a lot for your book and effort, I really appreciate that.

Thanks for your kind words.
Appreciate it.
If you are satisfied, your comment on Amazon will be a boost to the book.
If possible, do put in your words in Amazon, its a humble request.

Thanks once again
